[2025-01-26 17:35:08,137: INFO: main: welcome to cnnClassifier]
[2025-02-15 11:00:40,117: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-15 11:00:40,152: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-15 11:00:40,158: INFO: common: created directory at: artifacts]
[2025-02-15 11:00:40,159: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-15 11:00:56,095: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-15 11:13:42,076: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-15 11:13:42,084: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-15 11:13:42,086: INFO: common: created directory at: artifacts]
[2025-02-15 11:16:28,764: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-15 11:16:28,775: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-15 11:16:28,783: INFO: common: created directory at: artifacts]
[2025-02-15 11:16:28,789: INFO: common: created directory at: artifacts\training]
[2025-02-15 11:23:10,555: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-15 11:23:10,570: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-15 11:23:10,575: INFO: common: created directory at: artifacts]
[2025-02-15 11:23:10,580: INFO: common: created directory at: artifacts\training]
[2025-02-15 12:08:48,608: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-15 12:08:48,652: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-15 12:08:48,658: INFO: common: created directory at: artifacts]
[2025-02-15 12:08:48,662: INFO: common: created directory at: artifacts\training]
[2025-02-15 15:07:42,309: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-15 15:07:42,343: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-15 15:07:42,348: INFO: common: created directory at: artifacts]
[2025-02-15 15:08:22,650: INFO: common: json file saved at: scores.json]
[2025-02-15 15:08:30,688: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-02-15 15:08:32,036: INFO: builder_impl: Assets written to: C:\Users\chann\AppData\Local\Temp\tmp38hdc0tf\model\data\model\assets]
[2025-02-15 15:12:12,406: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-15 15:12:12,420: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-15 15:12:12,429: INFO: common: created directory at: artifacts]
[2025-02-15 15:12:44,596: INFO: common: json file saved at: scores.json]
[2025-02-15 15:12:47,913: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-02-15 15:12:48,730: INFO: builder_impl: Assets written to: C:\Users\chann\AppData\Local\Temp\tmprv31q3zm\model\data\model\assets]
[2025-02-15 15:24:43,656: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/channawarshri/End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD "HTTP/1.1 200 OK"]
[2025-02-15 15:24:43,698: INFO: helpers: Initialized MLflow to track repo "channawarshri/End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD"]
[2025-02-15 15:24:43,703: INFO: helpers: Repository channawarshri/End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD initialized!]
[2025-02-15 15:24:50,265: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-15 15:24:50,284: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-15 15:24:50,289: INFO: common: created directory at: artifacts]
[2025-02-15 15:25:15,038: INFO: common: json file saved at: scores.json]
[2025-02-15 15:25:21,995: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2025-02-15 15:25:22,740: INFO: builder_impl: Assets written to: C:\Users\chann\AppData\Local\Temp\tmpddbk96v1\model\data\model\assets]
[2025-02-15 16:10:54,905: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-15 16:10:54,908: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-15 16:10:54,910: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-15 16:10:54,911: INFO: common: created directory at: artifacts]
[2025-02-15 16:10:54,913: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-15 16:10:54,914: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1hxjw3DiQuzBCIiehk5ZI0pGR62e6JJQT/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-02-15 16:11:10,613: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1hxjw3DiQuzBCIiehk5ZI0pGR62e6JJQT/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-02-15 16:11:11,529: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-15 18:45:00,721: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-15 18:45:00,731: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-15 18:45:00,734: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-15 18:45:00,735: INFO: common: created directory at: artifacts]
[2025-02-15 18:45:00,736: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-15 18:45:00,737: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1hxjw3DiQuzBCIiehk5ZI0pGR62e6JJQT/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-02-15 18:45:16,199: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1hxjw3DiQuzBCIiehk5ZI0pGR62e6JJQT/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-02-15 18:45:16,683: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-15 18:45:39,612: INFO: stage_02_prepare_base_model: *******************]
[2025-02-15 18:45:39,613: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-15 18:45:39,616: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-15 18:45:39,619: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-15 18:45:39,622: INFO: common: created directory at: artifacts]
[2025-02-15 18:45:39,623: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-15 18:45:40,399: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-15 18:45:41,894: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-15 18:48:58,131: INFO: stage_02_prepare_base_model: *******************]
[2025-02-15 18:48:58,132: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-15 18:48:58,134: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-15 18:48:58,136: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-15 18:48:58,136: INFO: common: created directory at: artifacts]
[2025-02-15 18:48:58,137: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-15 18:48:58,830: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-15 18:48:59,183: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-15 18:49:08,023: INFO: stage_03_model_trainer: *******************]
[2025-02-15 18:49:08,024: INFO: stage_03_model_trainer: >>>>>> stage Training started <<<<<<]
[2025-02-15 18:49:08,027: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-15 18:49:08,028: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-15 18:49:08,029: INFO: common: created directory at: artifacts]
[2025-02-15 18:49:08,029: INFO: common: created directory at: artifacts\training]
[2025-02-15 19:40:08,113: INFO: stage_03_model_trainer: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-15 19:42:34,501: INFO: stage_03_model_trainer: *******************]
[2025-02-15 19:42:34,502: INFO: stage_03_model_trainer: >>>>>> stage Training started <<<<<<]
[2025-02-15 19:42:34,505: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-15 19:42:34,508: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-15 19:42:34,509: INFO: common: created directory at: artifacts]
[2025-02-15 19:42:34,511: INFO: common: created directory at: artifacts\training]
[2025-02-15 20:40:31,530: INFO: stage_03_model_trainer: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-15 20:40:50,289: INFO: stage_04_model_evaluation: *******************]
[2025-02-15 20:40:50,290: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-15 20:40:50,294: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-15 20:40:50,296: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-15 20:40:50,297: INFO: common: created directory at: artifacts]
[2025-02-15 20:41:07,555: INFO: common: json file saved at: scores.json]
[2025-02-15 20:41:07,556: INFO: common: json file saved at: scores.json]
[2025-02-15 20:41:07,556: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-02-15 21:12:25,947: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.6:8080]
[2025-02-15 21:12:25,948: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-02-15 21:12:50,598: INFO: _internal: 192.168.1.6 - - [15/Feb/2025 21:12:50] "GET / HTTP/1.1" 200 -]
[2025-02-15 21:13:24,450: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\app.py", line 46, in predictRoute
    result = clApp.classifier.predict()
  File "e:\final_year_project\end-to-end-chest-cancer-prediction-implementation-using-mlops-dvc-cicd\src\cnnClassifier\pipeline\prediction.py", line 18, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2025-02-15 21:13:24,622: INFO: _internal: 192.168.1.6 - - [15/Feb/2025 21:13:24] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-02-15 21:16:09,628: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.6:8080]
[2025-02-15 21:16:09,629: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-02-15 21:16:15,869: INFO: _internal: 192.168.1.6 - - [15/Feb/2025 21:16:15] "GET / HTTP/1.1" 200 -]
[2025-02-15 21:16:27,081: INFO: _internal: 192.168.1.6 - - [15/Feb/2025 21:16:27] "POST /predict HTTP/1.1" 200 -]
[2025-02-16 20:06:05,135: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.6:8080]
[2025-02-16 20:06:05,136: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-02-16 20:06:14,748: INFO: _internal: 192.168.1.6 - - [16/Feb/2025 20:06:14] "GET / HTTP/1.1" 200 -]
[2025-02-16 20:06:33,854: INFO: _internal: 192.168.1.6 - - [16/Feb/2025 20:06:33] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 10:11:23,201: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.25.6.71:8080]
[2025-02-17 10:11:23,202: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-02-17 10:14:25,919: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 10:14:25] "GET / HTTP/1.1" 200 -]
[2025-02-17 10:17:22,026: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 10:17:22] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 11:40:49,938: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.25.6.71:8080]
[2025-02-17 11:40:49,940: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-02-17 11:46:03,521: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 11:46:03] "GET / HTTP/1.1" 200 -]
[2025-02-17 11:48:44,396: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 11:48:44] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 11:49:50,795: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 11:49:50] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 11:49:56,695: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 11:49:56] "GET / HTTP/1.1" 200 -]
[2025-02-17 11:50:10,655: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 11:50:10] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 11:50:32,081: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 11:50:32] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 11:52:51,288: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001FDC3D5EEF0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-02-17 11:52:51,332: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 11:52:51] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 11:52:56,725: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 11:52:56] "GET / HTTP/1.1" 200 -]
[2025-02-17 11:55:56,525: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001FDC3D5ECB0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-02-17 11:55:56,568: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 11:55:56] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 11:57:08,330: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 11:57:08] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 11:57:30,769: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-17 11:57:30,769: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 11:57:30,785: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 11:57:30,785: INFO: common: created directory at: artifacts]
[2025-02-17 11:57:30,785: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-17 11:57:30,785: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1hxjw3DiQuzBCIiehk5ZI0pGR62e6JJQT/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-02-17 11:57:48,499: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1hxjw3DiQuzBCIiehk5ZI0pGR62e6JJQT/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-02-17 11:57:49,259: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-17 11:58:48,745: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 11:58:48,753: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 11:58:48,761: INFO: common: created directory at: artifacts]
[2025-02-17 11:58:48,761: INFO: common: created directory at: artifacts\training]
[2025-02-17 12:06:27,678: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.25.6.71:8080]
[2025-02-17 12:06:27,682: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-02-17 12:06:34,065: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 12:06:34] "GET / HTTP/1.1" 200 -]
[2025-02-17 12:07:16,105: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 12:07:16] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 12:07:29,286: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 12:07:29] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 12:07:33,955: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 12:07:33] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 12:19:53,040: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.25.6.71:8080]
[2025-02-17 12:19:53,041: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-02-17 12:20:03,830: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 12:20:03] "GET / HTTP/1.1" 200 -]
[2025-02-17 12:20:14,312: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 12:20:14] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 12:24:35,507: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.25.6.71:8080]
[2025-02-17 12:24:35,508: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-02-17 12:24:44,955: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 12:24:44] "GET / HTTP/1.1" 200 -]
[2025-02-17 12:24:56,909: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 12:24:56] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 12:25:42,951: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 12:25:42] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 12:25:52,409: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 12:25:52] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 12:26:45,584: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 12:26:45] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 12:26:48,463: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000021E00122DD0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-02-17 12:26:48,468: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 12:26:48] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 12:27:41,595: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 12:27:41,607: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 12:27:41,612: INFO: common: created directory at: artifacts]
[2025-02-17 12:27:41,617: INFO: common: created directory at: artifacts\training]
[2025-02-17 12:28:53,686: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 12:28:53,718: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 12:28:53,725: INFO: common: created directory at: artifacts]
[2025-02-17 12:28:53,735: INFO: common: created directory at: artifacts\training]
[2025-02-17 12:40:16,229: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.25.6.71:8080]
[2025-02-17 12:40:16,231: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-02-17 12:40:22,333: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 12:40:22] "GET / HTTP/1.1" 200 -]
[2025-02-17 12:40:32,718: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 12:40:32] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 12:40:49,785: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 12:40:49] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 12:40:57,638: INFO: _internal: 172.25.6.71 - - [17/Feb/2025 12:40:57] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 12:41:55,631: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-17 12:41:55,634: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 12:41:55,636: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 12:41:55,637: INFO: common: created directory at: artifacts]
[2025-02-17 12:41:55,638: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-17 12:41:55,639: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1hxjw3DiQuzBCIiehk5ZI0pGR62e6JJQT/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-02-17 12:42:14,846: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1hxjw3DiQuzBCIiehk5ZI0pGR62e6JJQT/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-02-17 12:42:15,320: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-17 13:56:07,778: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-17 13:56:07,782: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 13:56:07,786: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 13:56:07,788: INFO: common: created directory at: artifacts]
[2025-02-17 13:56:07,789: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-17 13:56:07,791: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SA4UUMQuR4rB2wPXcAgs5wn9i76iUx4V/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-17 13:56:38,676: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SA4UUMQuR4rB2wPXcAgs5wn9i76iUx4V/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-17 13:56:41,465: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-17 13:59:07,460: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-17 13:59:07,486: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 13:59:07,490: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 13:59:07,491: INFO: common: created directory at: artifacts]
[2025-02-17 13:59:07,492: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-17 13:59:07,493: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SA4UUMQuR4rB2wPXcAgs5wn9i76iUx4V/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-17 13:59:44,042: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SA4UUMQuR4rB2wPXcAgs5wn9i76iUx4V/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-02-17 13:59:46,757: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-17 14:02:30,890: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 14:02:30,894: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 14:02:30,897: INFO: common: created directory at: artifacts]
[2025-02-17 14:02:30,899: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-17 14:02:30,902: INFO: 1983665874: Downloading data from https://drive.google.com/file/d/1SA4UUMQuR4rB2wPXcAgs5wn9i76iUx4V/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-02-17 14:03:02,373: INFO: 1983665874: Downloaded data from https://drive.google.com/file/d/1SA4UUMQuR4rB2wPXcAgs5wn9i76iUx4V/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-02-17 14:03:48,548: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 14:03:48,555: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 14:03:48,563: INFO: common: created directory at: artifacts]
[2025-02-17 14:03:48,572: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-17 14:03:49,565: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-17 14:07:47,002: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 14:07:47,008: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 14:07:47,010: INFO: common: created directory at: artifacts]
[2025-02-17 14:07:47,012: INFO: common: created directory at: artifacts\training]
[2025-02-17 14:09:49,820: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 14:09:49,825: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 14:09:49,827: INFO: common: created directory at: artifacts]
[2025-02-17 14:09:49,828: INFO: common: created directory at: artifacts\training]
[2025-02-17 14:18:16,832: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 14:18:16,860: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 14:18:16,866: INFO: common: created directory at: artifacts]
[2025-02-17 14:18:16,869: INFO: common: created directory at: artifacts\training]
[2025-02-17 14:22:42,047: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 14:22:42,059: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 14:22:42,062: INFO: common: created directory at: artifacts]
[2025-02-17 14:22:42,064: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-17 14:22:42,986: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-17 14:23:05,110: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 14:23:05,123: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 14:23:05,129: INFO: common: created directory at: artifacts]
[2025-02-17 14:23:05,135: INFO: common: created directory at: artifacts\training]
[2025-02-17 14:59:49,034: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.6:8080]
[2025-02-17 14:59:49,034: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-02-17 14:59:56,895: INFO: _internal: 192.168.1.6 - - [17/Feb/2025 14:59:56] "GET / HTTP/1.1" 200 -]
[2025-02-17 15:00:37,165: INFO: _internal: 192.168.1.6 - - [17/Feb/2025 15:00:37] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 15:01:10,267: INFO: _internal: 192.168.1.6 - - [17/Feb/2025 15:01:10] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 15:01:19,061: INFO: _internal: 192.168.1.6 - - [17/Feb/2025 15:01:19] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 15:01:42,776: INFO: _internal: 192.168.1.6 - - [17/Feb/2025 15:01:42] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 15:02:02,360: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001B40E92EA70> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-02-17 15:02:02,364: INFO: _internal: 192.168.1.6 - - [17/Feb/2025 15:02:02] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 15:02:16,714: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001B40E92EE60> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-02-17 15:02:16,755: INFO: _internal: 192.168.1.6 - - [17/Feb/2025 15:02:16] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 15:02:31,057: INFO: _internal: 192.168.1.6 - - [17/Feb/2025 15:02:31] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 15:11:39,833: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.6:8080]
[2025-02-17 15:11:39,833: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-02-17 15:11:44,588: INFO: _internal: 192.168.1.6 - - [17/Feb/2025 15:11:44] "GET / HTTP/1.1" 200 -]
[2025-02-17 15:11:51,807: INFO: _internal: 192.168.1.6 - - [17/Feb/2025 15:11:51] "POST /predict HTTP/1.1" 200 -]
[2025-02-17 15:15:45,564: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 15:15:45,604: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 15:15:45,613: INFO: common: created directory at: artifacts]
[2025-02-17 15:15:45,631: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-17 15:15:47,031: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-17 15:16:23,414: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 15:16:23,492: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 15:16:23,502: INFO: common: created directory at: artifacts]
[2025-02-17 15:16:23,510: INFO: common: created directory at: artifacts\training]
[2025-02-17 15:16:36,072: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 15:16:36,084: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 15:16:36,088: INFO: common: created directory at: artifacts]
[2025-02-17 15:16:36,093: INFO: common: created directory at: artifacts\training]
[2025-02-17 15:19:58,104: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 15:19:58,110: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 15:19:58,112: INFO: common: created directory at: artifacts]
[2025-02-17 15:19:58,114: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-17 15:19:59,022: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-17 15:20:12,322: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 15:20:12,329: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 15:20:12,332: INFO: common: created directory at: artifacts]
[2025-02-17 15:20:12,335: INFO: common: created directory at: artifacts\training]
[2025-02-17 15:23:17,972: INFO: stage_02_prepare_base_model: *******************]
[2025-02-17 15:23:17,972: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-17 15:23:17,974: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 15:23:17,977: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 15:23:17,978: INFO: common: created directory at: artifacts]
[2025-02-17 15:23:17,978: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-17 15:23:18,829: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-17 15:23:19,761: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-17 15:23:48,470: INFO: stage_03_model_trainer: *******************]
[2025-02-17 15:23:48,471: INFO: stage_03_model_trainer: >>>>>> stage Training started <<<<<<]
[2025-02-17 15:23:48,478: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 15:23:48,487: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 15:23:48,489: INFO: common: created directory at: artifacts]
[2025-02-17 15:23:48,531: INFO: common: created directory at: artifacts\training]
[2025-02-17 15:23:49,764: ERROR: stage_03_model_trainer: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\Chest-CT-Scan-data']
Traceback (most recent call last):
  File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 30, in <module>
    obj.main()
  File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 20, in main
    training.train_valid_generator()
  File "e:\final_year_project\end-to-end-chest-cancer-prediction-implementation-using-mlops-dvc-cicd\src\cnnClassifier\components\model_trainer.py", line 38, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\Chest-CT-Scan-data'
[2025-02-17 15:24:11,265: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-17 15:24:11,270: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 15:24:11,275: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 15:24:11,276: INFO: common: created directory at: artifacts]
[2025-02-17 15:24:11,278: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-17 15:24:11,279: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SA4UUMQuR4rB2wPXcAgs5wn9i76iUx4V/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-02-17 15:24:42,376: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SA4UUMQuR4rB2wPXcAgs5wn9i76iUx4V/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-02-17 15:24:46,203: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-17 15:26:21,708: INFO: stage_03_model_trainer: *******************]
[2025-02-17 15:26:21,723: INFO: stage_03_model_trainer: >>>>>> stage Training started <<<<<<]
[2025-02-17 15:26:21,723: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 15:26:21,723: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 15:26:21,723: INFO: common: created directory at: artifacts]
[2025-02-17 15:26:21,723: INFO: common: created directory at: artifacts\training]
[2025-02-17 15:26:22,276: ERROR: stage_03_model_trainer: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\Chest-CT-Scan-data']
Traceback (most recent call last):
  File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 30, in <module>
    obj.main()
  File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 20, in main
    training.train_valid_generator()
  File "e:\final_year_project\end-to-end-chest-cancer-prediction-implementation-using-mlops-dvc-cicd\src\cnnClassifier\components\model_trainer.py", line 38, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\Chest-CT-Scan-data'
[2025-02-17 15:29:12,946: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 15:29:12,949: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 15:29:12,962: INFO: common: created directory at: artifacts]
[2025-02-17 15:29:12,967: INFO: common: created directory at: artifacts\training]
[2025-02-17 15:29:23,382: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 15:29:23,390: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 15:29:23,395: INFO: common: created directory at: artifacts]
[2025-02-17 15:29:23,397: INFO: common: created directory at: artifacts\training]
[2025-02-17 15:33:30,402: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 15:33:30,410: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 15:33:30,415: INFO: common: created directory at: artifacts]
[2025-02-17 15:33:30,419: INFO: common: created directory at: artifacts\training]
[2025-02-17 15:33:47,949: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 15:33:47,953: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 15:33:47,956: INFO: common: created directory at: artifacts]
[2025-02-17 15:33:47,958: INFO: common: created directory at: artifacts\training]
[2025-02-17 15:33:55,116: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 15:33:55,129: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 15:33:55,134: INFO: common: created directory at: artifacts]
[2025-02-17 15:33:55,138: INFO: common: created directory at: artifacts\training]
[2025-02-17 15:34:52,454: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 15:34:52,462: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 15:34:52,466: INFO: common: created directory at: artifacts]
[2025-02-17 15:34:52,469: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-17 15:34:53,291: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-17 15:35:10,588: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 15:35:10,597: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 15:35:10,601: INFO: common: created directory at: artifacts]
[2025-02-17 15:35:10,605: INFO: common: created directory at: artifacts\training]
[2025-02-17 15:38:30,759: INFO: stage_03_model_trainer: *******************]
[2025-02-17 15:38:30,759: INFO: stage_03_model_trainer: >>>>>> stage Training started <<<<<<]
[2025-02-17 15:38:30,759: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 15:38:30,759: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 15:38:30,759: INFO: common: created directory at: artifacts]
[2025-02-17 15:38:30,769: INFO: common: created directory at: artifacts\training]
[2025-02-17 15:38:31,779: ERROR: stage_03_model_trainer: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\Chest-CT-Scan-data']
Traceback (most recent call last):
  File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 30, in <module>
    obj.main()
  File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 20, in main
    training.train_valid_generator()
  File "e:\final_year_project\end-to-end-chest-cancer-prediction-implementation-using-mlops-dvc-cicd\src\cnnClassifier\components\model_trainer.py", line 38, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\Chest-CT-Scan-data'
[2025-02-17 15:45:09,293: INFO: stage_03_model_trainer: *******************]
[2025-02-17 15:45:09,293: INFO: stage_03_model_trainer: >>>>>> stage Training started <<<<<<]
[2025-02-17 15:45:09,293: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 15:45:09,293: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 15:45:09,293: INFO: common: created directory at: artifacts]
[2025-02-17 15:45:09,293: INFO: common: created directory at: artifacts\training]
[2025-02-17 15:45:16,002: ERROR: stage_03_model_trainer: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 30, in <module>
      obj.main()
    File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 21, in main
      training.train()
    File "e:\final_year_project\end-to-end-chest-cancer-prediction-implementation-using-mlops-dvc-cicd\src\cnnClassifier\components\model_trainer.py", line 77, in train
      self.model.fit(
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1051, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1109, in compute_loss
      return self.compiled_loss(
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\losses.py", line 1984, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\backend.py", line 5565, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[16,4] labels_size=[16,3]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_881]]
Traceback (most recent call last):
  File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 30, in <module>
    obj.main()
  File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 21, in main
    training.train()
  File "e:\final_year_project\end-to-end-chest-cancer-prediction-implementation-using-mlops-dvc-cicd\src\cnnClassifier\components\model_trainer.py", line 77, in train
    self.model.fit(
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 30, in <module>
      obj.main()
    File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 21, in main
      training.train()
    File "e:\final_year_project\end-to-end-chest-cancer-prediction-implementation-using-mlops-dvc-cicd\src\cnnClassifier\components\model_trainer.py", line 77, in train
      self.model.fit(
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1051, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1109, in compute_loss
      return self.compiled_loss(
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\losses.py", line 1984, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\backend.py", line 5565, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[16,4] labels_size=[16,3]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_881]
[2025-02-17 15:46:23,437: INFO: stage_02_prepare_base_model: *******************]
[2025-02-17 15:46:23,437: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-02-17 15:46:23,488: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 15:46:23,494: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 15:46:23,495: INFO: common: created directory at: artifacts]
[2025-02-17 15:46:23,498: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-02-17 15:46:24,303: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-17 15:46:24,945: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-02-17 15:47:54,072: INFO: stage_03_model_trainer: *******************]
[2025-02-17 15:47:54,072: INFO: stage_03_model_trainer: >>>>>> stage Training started <<<<<<]
[2025-02-17 15:47:54,072: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-02-17 15:47:54,072: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-17 15:47:54,072: INFO: common: created directory at: artifacts]
[2025-02-17 15:47:54,086: INFO: common: created directory at: artifacts\training]
[2025-02-17 15:48:03,287: ERROR: stage_03_model_trainer: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 30, in <module>
      obj.main()
    File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 21, in main
      training.train()
    File "e:\final_year_project\end-to-end-chest-cancer-prediction-implementation-using-mlops-dvc-cicd\src\cnnClassifier\components\model_trainer.py", line 77, in train
      self.model.fit(
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1051, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1109, in compute_loss
      return self.compiled_loss(
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\losses.py", line 1984, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\backend.py", line 5565, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[16,4] labels_size=[16,3]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_881]]
Traceback (most recent call last):
  File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 30, in <module>
    obj.main()
  File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 21, in main
    training.train()
  File "e:\final_year_project\end-to-end-chest-cancer-prediction-implementation-using-mlops-dvc-cicd\src\cnnClassifier\components\model_trainer.py", line 77, in train
    self.model.fit(
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 30, in <module>
      obj.main()
    File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 21, in main
      training.train()
    File "e:\final_year_project\end-to-end-chest-cancer-prediction-implementation-using-mlops-dvc-cicd\src\cnnClassifier\components\model_trainer.py", line 77, in train
      self.model.fit(
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1051, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1109, in compute_loss
      return self.compiled_loss(
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\losses.py", line 1984, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\backend.py", line 5565, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[16,4] labels_size=[16,3]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_881]
[2025-03-20 22:19:05,225: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.71:8080]
[2025-03-20 22:19:05,227: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-20 22:19:29,013: INFO: _internal: 127.0.0.1 - - [20/Mar/2025 22:19:29] "GET / HTTP/1.1" 200 -]
[2025-03-20 22:20:29,174: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\app.py\", line 46, in predictRoute
    result = clApp.classifier.predict()
  File "e:\final_year_project\end-to-end-chest-cancer-prediction-implementation-using-mlops-dvc-cicd\src\cnnClassifier\pipeline\prediction.py", line 17, in predict
    model = load_model(os.path.join("artifacts","training", "model.h5"))
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at artifacts\training\model.h5
[2025-03-20 22:20:29,256: INFO: _internal: 127.0.0.1 - - [20/Mar/2025 22:20:29] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-03-20 22:24:27,283: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.71:8080]
[2025-03-20 22:24:27,283: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-20 22:24:34,188: INFO: _internal: 127.0.0.1 - - [20/Mar/2025 22:24:34] "GET / HTTP/1.1" 200 -]
[2025-03-20 22:24:43,243: INFO: _internal: 127.0.0.1 - - [20/Mar/2025 22:24:43] "POST /predict HTTP/1.1" 200 -]
[2025-03-20 22:26:00,193: INFO: _internal: 127.0.0.1 - - [20/Mar/2025 22:26:00] "GET / HTTP/1.1" 200 -]
[2025-03-20 22:26:15,645: INFO: _internal: 127.0.0.1 - - [20/Mar/2025 22:26:15] "POST /predict HTTP/1.1" 200 -]
[2025-03-20 22:30:11,891: INFO: _internal: 127.0.0.1 - - [20/Mar/2025 22:30:11] "POST /predict HTTP/1.1" 200 -]
[2025-03-20 22:30:14,060: INFO: _internal: 127.0.0.1 - - [20/Mar/2025 22:30:14] "POST /predict HTTP/1.1" 200 -]
[2025-03-20 22:30:33,322: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000024790BEE830> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-03-20 22:30:33,336: INFO: _internal: 127.0.0.1 - - [20/Mar/2025 22:30:33] "POST /predict HTTP/1.1" 200 -]
[2025-03-20 22:33:12,913: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000024790BEEC20> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-03-20 22:33:12,953: INFO: _internal: 127.0.0.1 - - [20/Mar/2025 22:33:12] "POST /predict HTTP/1.1" 200 -]
[2025-04-11 09:29:53,154: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.5:8080]
[2025-04-11 09:29:53,154: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-04-11 09:30:06,755: INFO: _internal: 192.168.1.5 - - [11/Apr/2025 09:30:06] "GET / HTTP/1.1" 200 -]
[2025-04-11 09:30:16,004: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\app.py", line 46, in predictRoute
    result = clApp.classifier.predict()
  File "e:\final_year_project\end-to-end-chest-cancer-prediction-implementation-using-mlops-dvc-cicd\src\cnnClassifier\pipeline\prediction.py", line 21, in predict
    test_image = image.load_img(imagename, target_size = (224,224))
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\utils\image_utils.py", line 423, in load_img
    img = pil_image.open(io.BytesIO(f.read()))
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\PIL\Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x0000025422469350>
[2025-04-11 09:30:16,146: INFO: _internal: 192.168.1.5 - - [11/Apr/2025 09:30:16] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-04-11 09:30:20,571: INFO: _internal: 192.168.1.5 - - [11/Apr/2025 09:30:20] "GET / HTTP/1.1" 200 -]
[2025-04-11 09:30:43,831: INFO: _internal: 192.168.1.5 - - [11/Apr/2025 09:30:43] "POST /predict HTTP/1.1" 200 -]
[2025-04-11 09:34:31,366: INFO: _internal: 192.168.1.5 - - [11/Apr/2025 09:34:31] "POST /predict HTTP/1.1" 200 -]
[2025-04-11 09:34:34,382: INFO: _internal: 192.168.1.5 - - [11/Apr/2025 09:34:34] "POST /predict HTTP/1.1" 200 -]
[2025-04-11 09:34:35,390: INFO: _internal: 192.168.1.5 - - [11/Apr/2025 09:34:35] "GET / HTTP/1.1" 200 -]
[2025-04-11 09:34:46,907: INFO: _internal: 192.168.1.5 - - [11/Apr/2025 09:34:46] "POST /predict HTTP/1.1" 200 -]
[2025-04-11 09:35:04,318: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000254257A3F40> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-04-11 09:35:04,318: INFO: _internal: 192.168.1.5 - - [11/Apr/2025 09:35:04] "POST /predict HTTP/1.1" 200 -]
[2025-04-11 09:35:15,335: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000254257A3760> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-04-11 09:35:15,352: INFO: _internal: 192.168.1.5 - - [11/Apr/2025 09:35:15] "POST /predict HTTP/1.1" 200 -]
[2025-05-02 16:43:03,760: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-02 16:43:03,760: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-02 16:43:03,779: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-02 16:43:03,780: INFO: common: created directory at: artifacts]
[2025-05-02 16:43:03,781: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-02 16:43:03,782: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SA4UUMQuR4rB2wPXcAgs5wn9i76iUx4V/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-05-02 16:43:40,426: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SA4UUMQuR4rB2wPXcAgs5wn9i76iUx4V/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-05-02 16:43:41,612: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-02 16:48:21,345: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-05-02 16:48:21,345: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-02 16:48:21,352: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-02 16:48:21,352: INFO: common: created directory at: artifacts]
[2025-05-02 16:48:21,352: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-02 16:48:21,352: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SA4UUMQuR4rB2wPXcAgs5wn9i76iUx4V/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-05-02 16:49:02,073: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SA4UUMQuR4rB2wPXcAgs5wn9i76iUx4V/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-05-02 16:49:03,194: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-05-02 16:49:30,805: INFO: stage_02_prepare_base_model: *******************]
[2025-05-02 16:49:30,805: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-05-02 16:49:30,805: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-02 16:49:30,805: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-02 16:49:30,805: INFO: common: created directory at: artifacts]
[2025-05-02 16:49:30,805: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-02 16:49:31,561: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-02 16:49:31,855: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-02 16:54:50,341: INFO: stage_02_prepare_base_model: *******************]
[2025-05-02 16:54:50,341: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-05-02 16:54:50,341: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-02 16:54:50,341: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-02 16:54:50,341: INFO: common: created directory at: artifacts]
[2025-05-02 16:54:50,341: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-02 16:54:50,738: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-02 16:54:51,005: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-02 16:55:50,378: INFO: stage_03_model_trainer: *******************]
[2025-05-02 16:55:50,378: INFO: stage_03_model_trainer: >>>>>> stage Training started <<<<<<]
[2025-05-02 16:55:50,394: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-02 16:55:50,394: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-02 16:55:50,394: INFO: common: created directory at: artifacts]
[2025-05-02 16:55:50,401: INFO: common: created directory at: artifacts\training]
[2025-05-02 16:55:55,805: ERROR: stage_03_model_trainer: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 30, in <module>
      obj.main()
    File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 21, in main
      training.train()
    File "e:\final_year_project\end-to-end-chest-cancer-prediction-implementation-using-mlops-dvc-cicd\src\cnnClassifier\components\model_trainer.py", line 77, in train
      self.model.fit(
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1051, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1109, in compute_loss
      return self.compiled_loss(
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\losses.py", line 1984, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\backend.py", line 5565, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[16,4] labels_size=[16,3]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_881]]
Traceback (most recent call last):
  File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 30, in <module>
    obj.main()
  File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 21, in main
    training.train()
  File "e:\final_year_project\end-to-end-chest-cancer-prediction-implementation-using-mlops-dvc-cicd\src\cnnClassifier\components\model_trainer.py", line 77, in train
    self.model.fit(
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 30, in <module>
      obj.main()
    File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 21, in main
      training.train()
    File "e:\final_year_project\end-to-end-chest-cancer-prediction-implementation-using-mlops-dvc-cicd\src\cnnClassifier\components\model_trainer.py", line 77, in train
      self.model.fit(
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1051, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\training.py", line 1109, in compute_loss
      return self.compiled_loss(
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\losses.py", line 1984, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\backend.py", line 5565, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[16,4] labels_size=[16,3]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_881]
[2025-05-02 17:13:06,472: INFO: stage_02_prepare_base_model: *******************]
[2025-05-02 17:13:06,472: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-05-02 17:13:06,472: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-02 17:13:06,472: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-02 17:13:06,472: INFO: common: created directory at: artifacts]
[2025-05-02 17:13:06,472: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-02 17:13:07,113: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-02 17:13:08,059: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-05-02 17:13:20,191: INFO: stage_03_model_trainer: *******************]
[2025-05-02 17:13:20,191: INFO: stage_03_model_trainer: >>>>>> stage Training started <<<<<<]
[2025-05-02 17:13:20,194: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-02 17:13:20,194: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-02 17:13:20,194: INFO: common: created directory at: artifacts]
[2025-05-02 17:13:20,194: INFO: common: created directory at: artifacts\training]
[2025-05-02 18:03:22,553: INFO: stage_03_model_trainer: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-02 18:16:17,076: INFO: stage_04_model_evaluation: *******************]
[2025-05-02 18:16:17,078: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2025-05-02 18:16:17,080: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-02 18:16:17,083: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-02 18:16:17,085: INFO: common: created directory at: artifacts]
[2025-05-02 18:16:54,612: INFO: common: json file saved at: scores.json]
[2025-05-02 18:16:54,612: INFO: common: json file saved at: scores.json]
[2025-05-02 18:16:54,612: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-06-03 13:53:59,514: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-06-03 13:53:59,514: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-03 13:53:59,514: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-03 13:53:59,514: INFO: common: created directory at: artifacts]
[2025-06-03 13:53:59,524: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-03 13:53:59,524: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1bjd7MJRw-BllIUCdfIDrlJ2ZTGcoAL_2/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-06-03 13:54:30,312: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1bjd7MJRw-BllIUCdfIDrlJ2ZTGcoAL_2/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2025-06-03 13:54:32,010: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-06-03 13:55:05,146: INFO: stage_02_prepare_base_model: *******************]
[2025-06-03 13:55:05,146: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-06-03 13:55:05,146: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-03 13:55:05,146: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-03 13:55:05,146: INFO: common: created directory at: artifacts]
[2025-06-03 13:55:05,146: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-06-03 13:55:05,639: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-06-03 13:55:05,963: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-06-03 13:55:14,272: INFO: stage_03_model_trainer: *******************]
[2025-06-03 13:55:14,272: INFO: stage_03_model_trainer: >>>>>> stage Training started <<<<<<]
[2025-06-03 13:55:14,272: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-03 13:55:14,272: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-03 13:55:14,272: INFO: common: created directory at: artifacts]
[2025-06-03 13:55:14,272: INFO: common: created directory at: artifacts\training]
[2025-06-03 14:03:37,314: INFO: stage_03_model_trainer: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-06-03 14:03:50,122: INFO: stage_04_model_evaluation: *******************]
[2025-06-03 14:03:50,122: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2025-06-03 14:03:50,122: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-03 14:03:50,122: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-03 14:03:50,122: INFO: common: created directory at: artifacts]
[2025-06-03 14:05:05,596: INFO: common: json file saved at: scores.json]
[2025-06-03 14:05:05,596: INFO: common: json file saved at: scores.json]
[2025-06-03 14:05:05,596: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-06-03 14:06:26,039: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.3:8080]
[2025-06-03 14:06:26,040: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-03 14:06:30,449: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 14:06:30] "GET / HTTP/1.1" 200 -]
[2025-06-03 14:06:47,634: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 14:06:47] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 14:07:08,893: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 14:07:08] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 14:07:17,678: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 14:07:17] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 14:26:20,686: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.3:8080]
[2025-06-03 14:26:20,701: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-03 14:26:25,861: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 14:26:25] "GET / HTTP/1.1" 200 -]
[2025-06-03 14:26:32,249: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\app.py", line 43, in predictRoute
    result = clApp.classifier.predict()
  File "e:\final_year_project\end-to-end-chest-cancer-prediction-implementation-using-mlops-dvc-cicd\src\cnnClassifier\pipeline\prediction.py", line 18, in predict
    test_image = image.load_img(imagename, target_size = (224,224))
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\utils\image_utils.py", line 423, in load_img
    img = pil_image.open(io.BytesIO(f.read()))
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\PIL\Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x0000022D9268BAB0>
[2025-06-03 14:26:32,346: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 14:26:32] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-03 14:27:22,436: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.3:8080]
[2025-06-03 14:27:22,436: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-03 14:27:26,478: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 14:27:26] "GET / HTTP/1.1" 200 -]
[2025-06-03 14:27:35,006: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 14:27:35] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 14:29:44,728: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 14:29:44] "GET / HTTP/1.1" 200 -]
[2025-06-03 14:29:53,199: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\app.py", line 43, in predictRoute
    result = clApp.classifier.predict()
  File "e:\final_year_project\end-to-end-chest-cancer-prediction-implementation-using-mlops-dvc-cicd\src\cnnClassifier\pipeline\prediction.py", line 14, in predict
    model = load_model(os.path.join("artifacts","training", "model.h5"))
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\base_layer.py", line 870, in from_config
    raise TypeError(
TypeError: Error when deserializing class 'InputLayer' using config={'batch_shape': [None, 224, 224, 3], 'dtype': 'float32', 'sparse': False, 'name': 'input_layer'}.

Exception encountered: Unrecognized keyword arguments: ['batch_shape']
[2025-06-03 14:29:53,262: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 14:29:53] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-03 14:30:56,131: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 14:30:56] "GET / HTTP/1.1" 200 -]
[2025-06-03 14:36:50,476: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.3:8080]
[2025-06-03 14:36:50,476: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-03 14:36:54,423: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 14:36:54] "GET / HTTP/1.1" 200 -]
[2025-06-03 14:37:08,004: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\app.py", line 43, in predictRoute
    result = clApp.classifier.predict()
  File "e:\final_year_project\end-to-end-chest-cancer-prediction-implementation-using-mlops-dvc-cicd\src\cnnClassifier\pipeline\prediction.py", line 13, in predict
    model = load_model(os.path.join("artifacts","training", "model.h5"), compile=False)
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\base_layer.py", line 870, in from_config
    raise TypeError(
TypeError: Error when deserializing class 'InputLayer' using config={'batch_shape': [None, 224, 224, 3], 'dtype': 'float32', 'sparse': False, 'name': 'input_layer'}.

Exception encountered: Unrecognized keyword arguments: ['batch_shape']
[2025-06-03 14:37:08,073: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 14:37:08] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-03 14:48:00,777: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.3:8080]
[2025-06-03 14:48:00,777: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-03 14:48:08,393: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 14:48:08] "GET / HTTP/1.1" 200 -]
[2025-06-03 14:48:14,168: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\app.py", line 43, in predictRoute
    result = clApp.classifier.predict()
  File "e:\final_year_project\end-to-end-chest-cancer-prediction-implementation-using-mlops-dvc-cicd\src\cnnClassifier\pipeline\prediction.py", line 14, in predict
    model = load_model(os.path.join("artifacts","training", "model.h5"), compile=False)
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\base_layer.py", line 870, in from_config
    raise TypeError(
TypeError: Error when deserializing class 'InputLayer' using config={'batch_shape': [None, 224, 224, 3], 'dtype': 'float32', 'sparse': False, 'name': 'input_layer'}.

Exception encountered: Unrecognized keyword arguments: ['batch_shape']
[2025-06-03 14:48:14,184: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 14:48:14] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-03 16:47:00,948: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.3:8080]
[2025-06-03 16:47:00,949: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-03 16:47:08,656: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 16:47:08] "GET / HTTP/1.1" 200 -]
[2025-06-03 16:47:13,153: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "E:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\app.py", line 43, in predictRoute
    result = clApp.classifier.predict()
  File "e:\final_year_project\end-to-end-chest-cancer-prediction-implementation-using-mlops-dvc-cicd\src\cnnClassifier\pipeline\prediction.py", line 14, in predict
    model = load_model(os.path.join("artifacts","training", "vgg16_chest_new_cancer.h5"), compile=False)
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "e:\Final_year_project\End-to-End-Chest-Cancer-Prediction-Implementation-using-MLOps-DVC-CICD\.conda\lib\site-packages\keras\engine\base_layer.py", line 870, in from_config
    raise TypeError(
TypeError: Error when deserializing class 'InputLayer' using config={'batch_shape': [None, 224, 224, 3], 'dtype': 'float32', 'sparse': False, 'name': 'input_layer_2'}.

Exception encountered: Unrecognized keyword arguments: ['batch_shape']
[2025-06-03 16:47:13,231: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 16:47:13] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-06-03 16:52:39,886: INFO: font_manager: generated new fontManager]
[2025-06-03 16:52:43,953: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.3:8080]
[2025-06-03 16:52:43,953: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-03 16:52:48,945: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 16:52:48] "GET / HTTP/1.1" 200 -]
[2025-06-03 16:53:07,230: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 16:53:07] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 16:53:24,347: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 16:53:24] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 16:53:54,377: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 16:53:54] "GET / HTTP/1.1" 200 -]
[2025-06-03 16:54:02,809: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 16:54:02] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 16:57:49,676: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.3:8080]
[2025-06-03 16:57:49,676: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-03 16:57:51,580: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 16:57:51] "GET / HTTP/1.1" 200 -]
[2025-06-03 16:58:00,617: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 16:58:00] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 16:58:47,734: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 16:58:47] "GET / HTTP/1.1" 200 -]
[2025-06-03 16:58:54,275: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 16:58:54] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 17:58:46,159: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.3:8080]
[2025-06-03 17:58:46,159: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-03 17:58:52,798: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 17:58:52] "GET / HTTP/1.1" 200 -]
[2025-06-03 17:59:21,303: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 17:59:21] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 18:00:18,298: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 18:00:18] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 18:00:28,576: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 18:00:28] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 18:00:37,298: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 18:00:37] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 18:01:00,727: WARNING: polymorphic_function: 5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000001CC1B0C1AB0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-06-03 18:01:00,761: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 18:01:00] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 18:02:08,030: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.3:8080]
[2025-06-03 18:02:08,030: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-03 18:02:15,375: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 18:02:15] "GET / HTTP/1.1" 200 -]
[2025-06-03 18:02:24,969: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 18:02:24] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 18:02:47,372: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 18:02:47] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 18:02:50,209: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 18:02:50] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 18:04:46,477: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.3:8080]
[2025-06-03 18:04:46,484: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-03 18:04:55,773: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 18:04:55] "GET / HTTP/1.1" 200 -]
[2025-06-03 18:05:06,121: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 18:05:06] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 18:05:21,707: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 18:05:21] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 18:06:27,384: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.3:8080]
[2025-06-03 18:06:27,384: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-03 18:06:45,439: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 18:06:45] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 18:07:04,182: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 18:07:04] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 18:14:58,319: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.3:8080]
[2025-06-03 18:14:58,319: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-03 18:15:22,818: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 18:15:22] "GET / HTTP/1.1" 200 -]
[2025-06-03 18:15:40,314: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 18:15:40] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 18:15:55,821: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 18:15:55] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 20:05:07,516: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.3:8080]
[2025-06-03 20:05:07,516: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-03 20:05:10,427: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 20:05:10] "GET / HTTP/1.1" 200 -]
[2025-06-03 20:05:21,257: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 20:05:21] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 20:05:35,537: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 20:05:35] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 20:05:37,879: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 20:05:37] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 20:06:45,879: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.3:8080]
[2025-06-03 20:06:45,879: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-06-03 20:06:50,821: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 20:06:50] "GET / HTTP/1.1" 200 -]
[2025-06-03 20:06:57,987: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 20:06:57] "POST /predict HTTP/1.1" 200 -]
[2025-06-03 20:07:12,445: INFO: _internal: 127.0.0.1 - - [03/Jun/2025 20:07:12] "POST /predict HTTP/1.1" 200 -]
